export const ja = {
  toast: {
    created: "作成しました",
    updated: "更新しました",
    saved: "保存しました",
    deleted: "削除しました",
    duplicated: "複製しました",
    uploaded: "アップロードしました",
    statusChanged: "ステータスを変更しました",
    settingsSaved: "設定を保存しました",
    loginSuccess: "ログインしました",
    loginFailed: "ログインに失敗しました",
    logoutSuccess: "ログアウトしました",
    passwordChanged: "パスワードを変更しました",
    createFailed: "作成に失敗しました。もう一度お試しください。",
    updateFailed: "更新に失敗しました。もう一度お試しください。",
    saveFailed: "保存に失敗しました。もう一度お試しください。",
    deleteFailed: "削除に失敗しました。もう一度お試しください。",
    uploadFailed: "アップロードに失敗しました。もう一度お試しください。",
    statusChangeFailed: "ステータスの変更に失敗しました。もう一度お試しください。",
    unexpectedError: "予期しないエラーが発生しました",
    networkError: "サーバーに接続できません",
    validationError: "入力内容を確認してください",
    requiredFieldsMissing: "必須項目が入力されていません",
    selectItemFirst: "項目を選択してください",
    processing: "処理中...",
  },
  common: {
    adminTitle: "Resto Hub CMS",
    search: "検索...",
    add: "新規追加",
    edit: "編集",
    delete: "削除",
    save: "保存",
    cancel: "キャンセル",
    confirm: "確認",
    status: "ステータス",
    actions: "操作",
    active: "有効",
    inactive: "無効",
    draft: "下書き",
    published: "公開中",
    archived: "アーカイブ",
    logout: "ログアウト",
    confirmLogout: "ログアウトの確認",
    logoutMessage:
      "Adminパネルからログアウトしてもよろしいですか？保存されていない変更は失われる可能性があります。",
    loggingOut: "ログアウト中...",
    language: "言語",
    saving: "保存中...",
    loading: "読み込み中...",
    imageRequired: "画像は必須です",
    previous: "前へ",
    next: "次へ",
    advancedOptions: "詳細オプション",
    positionLabel: "表示位置（任意）",
    positionHint: "空欄の場合は末尾に追加されます。並び替えはドラッグ＆ドロップが推奨です。",
    saved: "保存しました",
    created: "作成しました",
    orderUpdated: "表示順を更新しました",
    orderUpdateFailed: "表示順の更新に失敗しました",
    dragToReorder: "ドラッグして並び替え",
    reorder: "並び替え",
    reorderTitle: "表示順の変更",
    reorderHint: "ドラッグ＆ドロップで順序を変更し、「順序を保存」を押してください。",
    reorderSelectCategory: "カテゴリーを選択してください",
    reorderEmpty: "並び替えできる項目がありません",
    saveOrder: "順序を保存",
  },
  sidebar: {
    dashboard: "ダッシュボード",
    homeManagement: "ホーム管理",
    foodMenu: "フードメニュー",
    drinkMenu: "ドリンクメニュー",
    buffetMenu: "ビュッフェメニュー",
    beerArt: "ビアアート",
    mediaCoverage: "メディア露出",
    touristGuide: "観光ガイド",
    challenge: "型抜きチャレンジ",
    faq: "よくある質問",
    restaurantInfo: "店舗情報",
    reservations: "予約管理",
    contactMessages: "お問い合わせ",
    analytics: "アナリティクス",
    mediaLibrary: "メディアライブラリ",
    settings: "設定",
  },
  foodMenu: {
    title: "フードメニュー管理",
    subtitle: "レストランの料理メニューアイテムとカテゴリーを管理します",
    addFood: "料理を追加",
    manageCategories: "カテゴリー管理",
    searchPlaceholder: "料理名で検索...",
    categoryFilter: "全カテゴリー",
    statusFilter: "全ステータス",
    noFoods: "料理が見つかりません",
    noFoodsDesc: "新しい料理を追加するか、検索・フィルター条件を変更してください。",
    editFood: "料理の編集",
    nameLabel: "料理名",
    descriptionLabel: "説明",
    priceLabel: "価格",
    originalPriceLabel: "元の価格",
    categoryLabel: "カテゴリー",
    selectCategory: "カテゴリーを選択",
    statusLabel: "ステータス",
    sortOrderLabel: "表示順",
    popularLabel: "人気メニュー",
    recommendedLabel: "おすすめメニュー",
    caloriesLabel: "カロリー (kcal)",
    ingredientsLabel: "材料",
    ingredientsPlaceholder: "例：豚バラ肉、キャベツ、卵、オリジナルソース",
    categoriesTitle: "フードカテゴリー",
    categoriesSubtitle: "ウェブメニューに表示されるカテゴリーと説明を管理します",
    editCategory: "カテゴリーを編集",
    addCategory: "新規カテゴリーを追加",
    descPlaceholder: "例：伝統的な日本のラーメン、焼き肉、前菜など。",
    descWithDisplay: "説明 (ウェブメニューに表示されます)",
    noDescription: "説明なし",
    itemsCount: "個のアイテム",
    deleteCategoryConfirm: "このカテゴリーを削除してもよろしいですか？",
    deleteConfirm: "このメニューを削除してもよろしいですか？",
    imageLabel: "画像",
    noImage: "画像なし",
    duplicate: "複製",
    showingPage: "{totalPages} ページ中 {page} ページ目を選択中 (合計 {total} アイテム)",
    previous: "前へ",
    next: "次へ",
    priceInclTax: "価格 (税込)",
  },
  drinkMenu: {
    title: "ドリンクメニュー管理",
    subtitle: "ドリンクメニューアイテムとカテゴリーを管理します",
    addDrink: "ドリンクを追加",
    manageCategories: "カテゴリー管理",
    searchPlaceholder: "ドリンク名で検索...",
    noDrinks: "ドリンクが見つかりません",
    categoryFilter: "全カテゴリー",
    statusFilter: "全ステータス",
    editDrink: "ドリンクの編集",
    nameLabel: "ドリンク名",
    descriptionLabel: "説明",
    priceLabel: "価格",
    pricePreview: "プレビュー",
    categoryLabel: "カテゴリー",
    selectCategory: "カテゴリーを選択",
    statusLabel: "ステータス",
    sortOrderLabel: "表示順",
    popularLabel: "人気メニュー",
    alcoholPercentLabel: "アルコール度数 %",
    volumeLabel: "容量",
    imageLabel: "画像",
    noImage: "画像なし",
    duplicate: "複製",
    showingPage: "{totalPages} ページ中 {page} ページ目を選択中 (合計 {total} アイテム)",
    previous: "前へ",
    next: "次へ",
    priceInclTax: "価格 (税込)",
    categoriesTitle: "ドリンクカテゴリー",
    categoriesSubtitle: "ウェブメニューに表示されるカテゴリーと説明を管理します",
    editCategory: "カテゴリーを編集",
    addCategory: "新規カテゴリーを追加",
    descPlaceholder: "例：厳選されたクラフトビールや季節の和酒。",
    descWithDisplay: "説明 (ウェブメニューに表示されます)",
    noDescription: "説明なし",
    itemsCount: "個のアイテム",
    deleteCategoryConfirm: "このカテゴリーを削除してもよろしいですか？",
    deleteConfirm: "このドリンクを削除してもよろしいですか？",
  },
  restaurantInfo: {
    title: "店舗情報管理",
    subtitle: "店舗の詳細情報、営業時間、SNSリンク、Googleマップの位置情報を管理します",
    name: "店舗名",
    slug: "スラッグ",
    description: "説明",
    address: "住所",
    phone: "電話番号",
    email: "メールアドレス",
    mapLocationTitle: "マップの位置情報 (Googleマップ)",
    mapInstruction:
      "Googleマップで店舗を検索し、ブラウザのアドレスバーからフルURLをコピーしてここに貼り付けてください。",
    pastePlaceholder: "https://www.google.com/maps/place/...",
    extract: "情報を抽出",
    extractedData: "抽出されたマップデータ",
    clearMapData: "マップデータをクリア",
    livePreview: "ライブプレビュー (ウェブサイトでの実際の表示です):",
    mapPlaceholder: "上の入力欄にGoogleマップ of リンクを貼り付けるとプレビューが表示されます",
    openingHoursTitle: "営業時間",
    openingHoursDesc: "曜日ごとの営業時間を設定します:",
    from: "開店:",
    to: "〜",
    closed: "定休日 (Closed)",
    days: {
      monday: "月曜日 (Monday)",
      tuesday: "火曜日 (Tuesday)",
      wednesday: "水曜日 (Wednesday)",
      thursday: "木曜日 (Thursday)",
      friday: "金曜日 (Friday)",
      saturday: "土曜日 (Saturday)",
      sunday: "日曜日 (Sunday)",
    },
    socialLinksTitle: "SNSリンク (Follow Us)",
    active: "有効",
    saveChanges: "変更を保存",
    saving: "保存中...",
    successMessage: "店舗情報が正常に更新されました！",
    errorMessage: "店舗情報の更新に失敗しました。",
    pricingTitle: "料金設定",
    taxRateLabel: "消費税率 (%)",
    taxRateHint: "メニュー価格の税込表示および全ての金額計算に使用されます",
  },
  touristGuide: {
    title: "観光ガイド",
    subtitle: "観光地とカテゴリーを管理します",
    placesTab: "観光地",
    categoriesTab: "カテゴリー",
    addPlace: "観光地を追加",
    addCategory: "カテゴリーを追加",
    editPlace: "観光地を編集",
    editCategory: "カテゴリーを編集",
    noPlaces: "観光地が登録されていません",
    noCategories: "カテゴリーが登録されていません",
    nameLabel: "名称",
    descriptionLabel: "説明",
    additionalImages: "追加の画像",
    categoryLabel: "カテゴリー",
    selectCategory: "カテゴリーを選択",
    noCategoryOption: "カテゴリーなし",
    addressLabel: "住所",
    openingHoursLabel: "営業時間",
    websiteUrlLabel: "ウェブサイト",
    googleMapUrlLabel: "Google マップ",
    publishedLabel: "公開中",
    sortOrderLabel: "表示順",
    deleteConfirm: "このアイテムを削除しますか？",
    showingPage: "{totalPages} ページ中 {page} ページ目を選択中 (合計 {total} アイテム)",
    previous: "前へ",
    next: "次へ",
  },
  imageUpload: {
    defaultLabel: "画像",
    defaultMultiLabel: "画像一覧",
    remove: "削除",
    uploading: "アップロード中...",
    dragDropSingle: "ドラッグ＆ドロップまたはクリックしてアップロード",
    dragDropMulti: "ドラッグ＆ドロップまたはクリックして画像を追加",
    orPasteUrl: "またはURLを貼り付け:",
    pastePlaceholder: "画像のURLを貼り付けてEnterキーを押します",
    add: "追加",
    pleaseSelectImage: "画像ファイルを選択してください",
    uploadFailed: "アップロードに失敗しました",
  },
  buffetMenu: {
    title: "食べ放題メニュー",
    subtitle: "食べ放題コースを管理します",
    addCourse: "コースを追加",
    searchPlaceholder: "コースを検索...",
    statusFilter: "全ステータス",
    noBuffets: "食べ放題コースが見つかりません",
    editCourse: "コースの編集",
    nameLabel: "コース名",
    descriptionLabel: "説明",
    priceLabel: "価格",
    durationLabel: "制限時間 (分)",
    minPeopleLabel: "最小人数",
    maxPeopleLabel: "最大人数",
    includesLabel: "含まれる内容",
    includesSelectorDesc: "下のメニューアイテムをクリックして追加または削除します",
    allMenuLabel: "店内全てのメニュー (全品対象)",
    allMenuDesc: "このコースは全メニューが対象です。個別に選択する必要はありません。",
    noIncludesSelected: "アイテムが選択されていません。下のメニューから選択してください。",
    searchMenuPlaceholder: "含めるメニューアイテムを検索...",
    noMenuItemsFound: "{type} アイテムが見つかりません",
    sortOrderLabel: "表示順",
    statusLabel: "ステータス",
    popularLabel: "人気メニュー",
    imageLabel: "画像",
    noImage: "画像なし",
    duplicate: "複製",
    showingPage: "{totalPages} ページ中 {page} ページ目を選択中 (合計 {total} アイテム)",
    previous: "前へ",
    next: "次へ",
    groupSize: "利用人数",
    groupSizeFormat: "{min}〜{max} 名様",
    minPeopleFormat: "最小 {min} 名様",
    maxPeopleFormat: "最大 {max} 名様",
    foodTab: "フード ({count})",
    drinkTab: "ドリンク ({count})",
    categoryTab: "カテゴリー ({count})",
    notesLabel: "注意書き",
    notesPlaceholder: "例：食べ飲み残し別途料金",
    notesHint: "1行につき1つの注意書き。各行はウェブで※付きで表示されます。",
    durationFormat: "{duration} 分",
    deleteConfirm: "このビュッフェコースを削除してもよろしいですか？",
  },
  beerArt: {
    title: "ビアアート",
    subtitle: "ビアアートギャラリーを管理します",
    addItem: "アートを追加",
    noItems: "ビアアートアイテムが見つかりません",
    editItem: "ビアアートの編集",
    titleLabel: "タイトル",
    descriptionLabel: "説明",
    customerNameLabel: "お客様名",
    artistNameLabel: "アーティスト名",
    popularLabel: "人気",
    publishedLabel: "公開済み",
    imageLabel: "画像",
    deleteConfirm: "このアイテムを削除してもよろしいですか？",
    noImage: "画像なし",
    showingPage: "{totalPages} ページ中 {page} ページ目を選択中 (合計 {total} アイテム)",
    previous: "前へ",
    next: "次へ",
  },
  mediaCoverage: {
    title: "メディア露出",
    subtitle: "メディア掲載記事と掲載メディアロゴを管理します",
    articlesTab: "掲載記事",
    outletsTab: "掲載メディア",
    addArticle: "記事を追加",
    editArticle: "記事を編集",
    addOutlet: "メディアを追加",
    editOutlet: "メディアを編集",
    noArticles: "掲載記事が見つかりません",
    noOutlets: "掲載メディアが見つかりません",
    searchPlaceholder: "タイトル・メディア名で検索...",
    categoryFilter: "カテゴリー",
    statusFilter: "ステータス",
    publishedDateLabel: "掲載日",
    mediaNameLabel: "メディア名",
    titleLabel: "タイトル",
    descriptionLabel: "紹介文",
    thumbnailLabel: "サムネイル画像",
    externalUrlLabel: "外部リンク",
    categoryLabel: "カテゴリ",
    selectCategory: "カテゴリを選択",
    categoryRequired: "カテゴリを選択してください",
    featuredLabel: "注目記事",
    featuredHint: "注目記事は1件のみ表示されます。他の注目記事は自動的に解除されます。",
    publishedLabel: "公開済み",
    outletNameLabel: "メディア名",
    outletLogoLabel: "ロゴ画像",
    outletWebsiteLabel: "ウェブサイトURL",
    activeLabel: "表示する",
    noImage: "画像なし",
    deleteArticleConfirm: "この掲載記事を削除してもよろしいですか？",
    deleteOutletConfirm: "この掲載メディアを削除してもよろしいですか？",
    showingPage: "{totalPages} ページ中 {page} ページ目 (合計 {total} 件)",
    previous: "前へ",
    next: "次へ",
    category: {
      TV: "TV",
      MAGAZINE: "雑誌",
      WEB: "Web",
      YOUTUBE: "YouTube",
      INFLUENCER: "インフルエンサー",
    },
  },
  faq: {
    title: "FAQ",
    subtitle: "よくある質問を管理します",
    addFaq: "質問を追加",
    addCategory: "カテゴリーを追加",
    editFaq: "質問を編集",
    editCategory: "カテゴリーを編集",
    questionsTab: "質問一覧",
    categoriesTab: "カテゴリー",
    noFaqs: "質問が登録されていません",
    noCategories: "カテゴリーが登録されていません",
    questionLabel: "質問 (Question)",
    answerLabel: "回答 (Answer)",
    categoryLabel: "カテゴリー",
    selectCategory: "カテゴリーを選択",
    sortOrderLabel: "表示順",
    publishedLabel: "公開済み",
    noCategoryOption: "カテゴリーなし",
    nameLabel: "名称",
    slugLabel: "スラグ",
    descriptionLabel: "説明",
    deleteConfirm: "このアイテムを削除してもよろしいですか？",
    orderLabel: "表示順",
    uncategorized: "未分類",
  },
  challenge: {
    title: "型抜きチャレンジ",
    subtitle: "チャレンジのルールと当選者リストを管理します",
    illustrationTitle: "チャレンジのイラスト・画像",
    illustrationSubtitle:
      "この画像は公開用の型抜きチャレンジページに表示されます。推奨サイズ：800x600px。",
    addRule: "ルールを追加",
    addWinner: "当選者を追加",
    editRule: "ルールを編集",
    editWinner: "当選者を編集",
    rulesTab: "ルール",
    winnersTab: "当選者一覧",
    noRules: "ルールが登録されていません",
    noWinners: "当選者が登録されていません",
    ruleTitleLabel: "タイトル",
    ruleDescriptionLabel: "説明",
    winnerNameLabel: "参加者名",
    winnerChallengeLabel: "型抜きの種類",
    winnerAwardLabel: "獲得割引",
    completedAtLabel: "達成日",
    sortOrderLabel: "表示順",
    activeLabel: "有効",
    publishedLabel: "公開中",
    imageLabel: "画像URL",
    deleteConfirm: "このアイテムを削除してもよろしいですか？",
    showingPage: "ページを表示中: {page} / {totalPages} (合計: {total} 件)",
  },
  settings: {
    title: "アカウント設定",
    subtitle: "プロフィール詳細の管理およびパスワードの変更",
    profileTitle: "プロフィール情報",
    passwordTitle: "パスワードの変更",
    username: "ユーザー名",
    email: "メールアドレス",
    newPassword: "新しいパスワード",
    confirmPassword: "新しいパスワード (確認)",
    updateSuccess: "プロフィールが更新されました！",
    passwordsNotMatch: "パスワードが一致しません",
    updating: "更新中...",
    saveChanges: "変更を保存",
  },
  homeManagement: {
    title: "ホーム管理",
    subtitle: "ヒーローバナーとイベントの管理",
    bannersTab: "バナー ({count})",
    eventsTab: "イベント ({count})",
    brandAssetsTab: "ブランドアセット",
    noBanners: "バナーが設定されていません。デフォルトのヒーロー画像を使用しています。",
    noEvents: "イベントが見つかりません",
    deleteBannerConfirm: "このバナーを削除しますか？",
    deleteEventConfirm: "このイベントを削除しますか？",
    brandingTitle: "ウェブサイトのブランディング",
    logoLabel: "ロゴ画像",
    faviconLabel: "ファビコン画像",
    saveSuccess: "ブランドアセットが正常に更新されました！",
    saveFailed: "ブランドアセットの更新に失敗しました",
    addBanner: "バナー追加",
    editBanner: "バナー編集",
    bannerTitle: "タイトル",
    bannerSubtitle: "サブタイトル",
    bannerImage: "バナー画像",
    bannerSortOrder: "表示順",
    bannerStatus: "有効状態",
    bannerCtaLabel: "CTAラベル (任意)",
    bannerCtaUrl: "CTAリンク (任意)",
    delete: "削除",
  },
  contact: {
    title: "メッセージ一覧",
    subtitle: "お問い合わせフォーム送信履歴の管理",
    allStatus: "すべてのステータス",
    new: "新規",
    inProgress: "対応中",
    resolved: "解決済み",
    closed: "クローズ",
    noMessages: "メッセージが見つかりません",
    fromLabel: "送信元",
    subjectLabel: "件名",
    statusLabel: "ステータス",
    dateLabel: "送信日",
    actionsLabel: "アクション",
    view: "表示",
    messageDetails: "メッセージ詳細",
    phoneLabel: "電話番号",
    messageLabel: "メッセージ本文",
    receivedLabel: "受信日時",
    deleteConfirm: "このメッセージを削除してもよろしいですか？",
    delete: "削除",
  },
  dashboard: {
    title: "ダッシュボード",
    welcome: "店舗管理システムへようこそ",
    loading: "読み込み中...",
    foodItems: "フードメニュー",
    drinkItems: "ドリンクメニュー",
    messages: "メッセージ",
    unread: "未読",
    todayViews: "本日の閲覧数",
    weekViews: "今週の閲覧数",
    totalViews: "累計閲覧数",
    uniqueVisitors: "訪問者",
    totalUniqueVisitors: "累計訪問者数",
    recentMessages: "最近のメッセージ",
    popularFoods: "人気の料理",
    viewAll: "すべて表示",
    manage: "管理",
    noMessages: "メッセージはありません",
    noFoods: "料理はありません",
  },
  analytics: {
    title: "アナリティクス",
    subtitle: "訪問者とコンテンツパフォーマンス",
    last7Days: "過去7日間",
    last30Days: "過去30日間",
    last90Days: "過去90日間",
    pageViews: "ページビュー",
    visitors: "訪問者数",
    vsPreviousPeriod: "前期比",
    dailyTrend: "日別トレンド",
    topCategories: "人気カテゴリ",
    topDishes: "人気メニュー",
    topCountries: "国別訪問者",
    noData: "この期間のデータはありません",
    exportCsv: "CSV出力",
    exportPdf: "PDF出力",
    popupBlocked: "ポップアップがブロックされました。許可してから再度お試しください",
    dateRange: "期間",
    generatedAt: "作成日時",
    metric: "指標",
    value: "値",
    change: "変化",
    rank: "順位",
    name: "名前",
    views: "閲覧数",
    share: "割合",
    country: "国",
    date: "日付",
  },
};

export default ja;
